CUDA_VISIBLE_DEVICES=0 python -m train.train_diffusion \
  --tfrecord_path /data/datasets/waymo/waymo-open-dataset-v1.3.1/tf_example/training/training_tfexample.tfrecord@1000 \
  --seed 42 \
  --batch_size 1536 \
  --shuffle_buffer_size 1536 \
  --dataset_num_shards 2 \
  --epochs 500 \
  --steps_per_epoch 65 \
  --save_every 10 \
  --save_dir ./train/checkpoints \
  --warmup_steps 2000 \
  --ema_update_every 1 \
  --hidden_dim 256 \
  --cond_dim 256 \
  --target_dim 5 \
  --predict_horizon 25 \
  --model_dt 0.2 \
  --log_every 1 \
  --pbar_every 1 \
  --log_jsonl_path ./train_logs.jsonl \
  --wandb_project waymax \
  --wandb_mode online \
  --jax_compilation_cache_dir .jax_compilation_cache
